version: "3"
services:
  spring-event:
    image: yassineghoul/event_image
    ports:
      - "8089:8089"
    networks:
      - event
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/eventsProject
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    volumes:
      -  /home/mysql/yassinedata:/var/lib/mysql:rw
    networks:
      - kaddem
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=eventsProject

networks:
  kaddem: